# Generated by Django 4.2.23 on 2025-08-08 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_class_year', models.CharField(blank=True, max_length=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('archived', 'Archived'), ('private', 'Private'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('content_type', models.CharField(choices=[('article', 'Article/Interview'), ('session', 'Session'), ('playlist', 'Playlist'), ('photography', 'Photography'), ('artwork', 'Artwork/Media'), ('event', 'Event Coverage')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('homepage_order', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('cover_image', models.ImageField(blank=True, upload_to='articles/')),
                ('article_type', models.CharField(choices=[('interview', 'Interview'), ('feature', 'Feature'), ('review', 'Review'), ('news', 'News')], default='feature', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_class_year', models.CharField(blank=True, max_length=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('archived', 'Archived'), ('private', 'Private'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('content_type', models.CharField(choices=[('article', 'Article/Interview'), ('session', 'Session'), ('playlist', 'Playlist'), ('photography', 'Photography'), ('artwork', 'Artwork/Media'), ('event', 'Event Coverage')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('homepage_order', models.PositiveIntegerField(default=0)),
                ('media_type', models.CharField(choices=[('photography', 'Photography'), ('artwork', 'Artwork'), ('poster', 'Poster'), ('video', 'Video')], max_length=20)),
                ('file', models.FileField(upload_to='media_files/')),
                ('file_size', models.CharField(blank=True, max_length=20)),
                ('dimensions', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_class_year', models.CharField(blank=True, max_length=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('archived', 'Archived'), ('private', 'Private'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('content_type', models.CharField(choices=[('article', 'Article/Interview'), ('session', 'Session'), ('playlist', 'Playlist'), ('photography', 'Photography'), ('artwork', 'Artwork/Media'), ('event', 'Event Coverage')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('homepage_order', models.PositiveIntegerField(default=0)),
                ('platform', models.CharField(choices=[('spotify', 'Spotify'), ('apple', 'Apple Music'), ('soundcloud', 'SoundCloud')], max_length=20)),
                ('playlist_url', models.URLField()),
                ('track_count', models.PositiveIntegerField(default=0)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('cover_color', models.CharField(default='#000000', max_length=7)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_class_year', models.CharField(blank=True, max_length=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('archived', 'Archived'), ('private', 'Private'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('content_type', models.CharField(choices=[('article', 'Article/Interview'), ('session', 'Session'), ('playlist', 'Playlist'), ('photography', 'Photography'), ('artwork', 'Artwork/Media'), ('event', 'Event Coverage')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('homepage_order', models.PositiveIntegerField(default=0)),
                ('session_type', models.CharField(choices=[('live', 'Live Performance'), ('dj_set', 'DJ Set'), ('interview', 'Interview Session')], max_length=20)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('video_url', models.URLField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='sessions/')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_class_year', models.CharField(blank=True, max_length=4)),
                ('content_type', models.CharField(choices=[('article', 'Article/Interview'), ('session', 'Session'), ('playlist', 'Playlist'), ('photography', 'Photography'), ('artwork', 'Artwork/Media'), ('event', 'Event Coverage')], max_length=20)),
                ('content_text', models.TextField(blank=True)),
                ('playlist_url', models.URLField(blank=True)),
                ('platform', models.CharField(blank=True, max_length=20)),
                ('files', models.FileField(blank=True, upload_to='submissions/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
