# Generated by Django 4.2.23 on 2025-08-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='creator_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='playlist',
            name='embed_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='genre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='playlist',
            name='platform_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='platform',
            field=models.CharField(choices=[('spotify', 'Spotify'), ('soundcloud', 'SoundCloud'), ('youtube', 'YouTube')], max_length=20),
        ),
    ]
