# Generated by Django 4.2.23 on 2025-08-08 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_playlist_creator_name_playlist_embed_html_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_featured_section', models.BooleanField(default=True)),
                ('show_sessions_section', models.BooleanField(default=True)),
                ('show_playlists_section', models.BooleanField(default=True)),
                ('sessions_count', models.PositiveIntegerField(default=3, help_text='Number of sessions to show')),
                ('playlists_count', models.PositiveIntegerField(default=4, help_text='Number of playlists to show')),
                ('sections_order', models.JSONField(default=list, help_text="Order of sections: ['featured', 'sessions', 'playlists']")),
                ('hero_title', models.CharField(blank=True, help_text='Custom hero title', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, help_text='Custom hero subtitle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_on_homepage', to='main.article')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Homepage Configuration',
                'verbose_name_plural': 'Homepage Configurations',
            },
        ),
        migrations.CreateModel(
            name='FeaturedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('session', 'Session'), ('playlist', 'Playlist'), ('media', 'Media')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('featured_on_homepage', models.BooleanField(default=False)),
                ('featured_in_section', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher numbers appear first')),
                ('featured_at', models.DateTimeField(auto_now_add=True)),
                ('featured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-featured_at'],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
