# Generated by Django 4.2.23 on 2025-08-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_homepageconfig_featuredcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageconfig',
            name='featured_button_text',
            field=models.CharField(default='Read Full Interview', help_text="Text for the call-to-action button (e.g., 'Read Interview', 'Watch Here', 'Listen Here')", max_length=50),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='featured_description',
            field=models.TextField(blank=True, help_text='Custom description for featured content (overrides article description)'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Custom image for featured content (auto-resized to fit layout)', null=True, upload_to='featured/'),
        ),
        migrations.AddField(
            model_name='homepageconfig',
            name='featured_title',
            field=models.CharField(blank=True, help_text='Custom title for featured content (overrides article title)', max_length=200),
        ),
    ]
