# Generated by Django 4.2.23 on 2025-08-08 09:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
