# Generated by Django 4.2.23 on 2025-08-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_session_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='duration',
        ),
    ]
