# Generated by Django 4.2.23 on 2025-08-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_session_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-custom_publication_date', '-published_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-custom_publication_date', '-published_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-custom_publication_date', '-published_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-custom_publication_date', '-published_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='article',
            name='custom_publication_date',
            field=models.DateField(blank=True, help_text='Set a custom publication date for archival content or backdating', null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='custom_publication_date',
            field=models.DateField(blank=True, help_text='Set a custom publication date for archival content or backdating', null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='custom_publication_date',
            field=models.DateField(blank=True, help_text='Set a custom publication date for archival content or backdating', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='custom_publication_date',
            field=models.DateField(blank=True, help_text='Set a custom publication date for archival content or backdating', null=True),
        ),
    ]
